### ISSUE TITLE
bower.json can only include the package with the "*" wildcard

### ISSUE THREAD

**Issue by rebelliard** [sparkalow/angular-truncate#27]
Currently, the library can only be specified in a `bower.json` package using the `*` wildcard instead of a specific version. As indicated on the following [article](http://bob.yexley.net/creating-and-maintaining-your-own-bower-package/), in order for bower to detect the package version, a git tag is required.

Could you add a version tag? 

``````
# tag the commit
git tag -a v0.1.2 -m "Release version 0.1.2"

# push to GitHub
git push origin master --tags```
``````

**Comment by BernardoSilva** [comment]
@rebelliard I've created a maintained for of this project.
Maybe you can use this one to solve your problems: https://github.com/BernardoSilva/angular-truncate

Hope it helps.
