### ISSUE TITLE
String with space throws off truncating

### ISSUE THREAD

**Issue by pisaacs** [sparkalow/angular-truncate#4]
{{'Florida/New Jersey/California/Texas' | characters:30}}

Returns:
Florida/New... 

Instead of:
Florida/New Jersey/California/...

**Comment by sparkalow** [comment]
The filter will not truncate in the middle of a word. I have added a parameter for the filter to control this behavior. Set it to force a break at the specified characters.

```
{{'Florida/New Jersey/California/Texas' | characters:30}}
```
