### ISSUE TITLE
Publish angular truncate through bower

### ISSUE THREAD

**Issue by apolishch** [sparkalow/angular-truncate#7]
Now that the project includes a bower.json. Could you please publish the project through bower?

**Comment by gregberge** [comment]
+1, you should tag your project.

**Comment by dapids** [comment]
+1

**Comment by pensierinmusica** [comment]
+1 Please reclaim the Bower package!!

I already opened an issue for it  :)

https://github.com/bower/bower/issues/1327

Anyone in this thread who feels it's right, please support it!

**Comment by pensierinmusica** [comment]
Btw, in the meantime I published a package named `angular-truncate-original` as a temporary solution until the issue with the Bower package maintainers is resolved.

**Comment by sparkalow** [comment]
bower install angular-truncate should now work
